export const GET_AVATAR_INGO = 'GET_AVATAR_INGO';
export const GET_AVATAR_SUCC = 'GET_AVATAR_SUCC';
export const GET_AVATAR_FAIL = 'GET_AVATAR_FAIL';

export const GET_SHOP_ITEMS_INGO = 'GET_SHOP_ITEMS_INGO';
export const GET_SHOP_ITEMS_SUCC = 'GET_SHOP_ITEMS_SUCC';
export const GET_SHOP_ITEMS_FAIL = 'GET_SHOP_ITEMS_FAIL';

export const MODIFY_FILTERS = 'MODIFY_FILTERS';
