export const GET_AVATAR_INGO = 'GET_AVATAR_INGO';
export const GET_AVATAR_SUCC = 'GET_AVATAR_SUCC';
export const GET_AVATAR_FAIL = 'GET_AVATAR_FAIL';

export const GET_SHOP_ITEMS_INGO = 'GET_SHOP_ITEMS_INGO';
export const GET_SHOP_ITEMS_SUCC = 'GET_SHOP_ITEMS_SUCC';
export const GET_SHOP_ITEMS_FAIL = 'GET_SHOP_ITEMS_FAIL';

export const GET_CHECKLIST_ITEMS_INGO = 'GET_CHECKLIST_ITEMS_INGO';
export const GET_CHECKLIST_ITEMS_SUCC = 'GET_CHECKLIST_ITEMS_SUCC';
export const GET_CHECKLIST_ITEMS_FAIL = 'GET_CHECKLIST_ITEMS_FAIL';


export const DELETE_CHECKLIST_ITEMS = 'DELETE_CHECKLIST_ITEMS';


export const MODIFY_FILTERS = 'MODIFY_FILTERS';
