export const GET_AVATAR_INGO = 'GET_AVATAR_INGO';
export const GET_AVATAR_SUCC = 'GET_AVATAR_SUCC';
export const GET_AVATAR_FAIL = 'GET_AVATAR_FAIL';

export const GET_SHOP_ITEMS_INGO = 'GET_SHOP_ITEMS_INGO';
export const GET_SHOP_ITEMS_SUCC = 'GET_SHOP_ITEMS_SUCC';
export const GET_SHOP_ITEMS_FAIL = 'GET_SHOP_ITEMS_FAIL';

export const GET_CHECKLIST_ITEMS_INGO = 'GET_CHECKLIST_ITEMS_INGO';
export const GET_CHECKLIST_ITEMS_SUCC = 'GET_CHECKLIST_ITEMS_SUCC';
export const GET_CHECKLIST_ITEMS_FAIL = 'GET_CHECKLIST_ITEMS_FAIL';

export const GET_DASHBOARD_CART_INGO = 'GET_DASHBOARD_CART_INGO';
export const GET_DASHBOARD_CART_SUCC = 'GET_DASHBOARD_CART_SUCC';
export const GET_DASHBOARD_CART_FAIL = 'GET_DASHBOARD_CART_FAIL';

export const POST_ADD_TO_CART_INGO = 'POST_ADD_TO_CART_INGO';
export const POST_ADD_TO_CART_SUCC = 'POST_ADD_TO_CART_SUCC';
export const POST_ADD_TO_CART_FAIL = 'POST_ADD_TO_CART_FAIL';

export const DELETE_CHECKLIST_ITEMS = 'DELETE_CHECKLIST_ITEMS';


export const MODIFY_FILTERS = 'MODIFY_FILTERS';
